# Generated by Django 3.1.2 on 2021-01-26 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20210123_1127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='address',
            new_name='default_address',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='city',
            new_name='default_city',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='country',
            new_name='default_country',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='phone_number',
            new_name='default_phone_number',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='postcode',
            new_name='default_postcode',
        ),
    ]
