# Generated by Django 3.1.2 on 2021-01-29 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog_category',
            options={'verbose_name_plural': 'blog Categories'},
        ),
        migrations.AddField(
            model_name='article',
            name='additionalImages',
            field=models.FileField(blank=True, default='', null=True, upload_to='articles/additional'),
        ),
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.FileField(blank=True, default='', null=True, upload_to='articles/img'),
        ),
        migrations.AddField(
            model_name='article',
            name='url',
            field=models.SlugField(default=None, max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='teaser',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
