# Generated by Django 3.1.2 on 2021-01-29 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='additionalImages',
            field=models.FileField(blank=True, default='', null=True, upload_to='additional'),
        ),
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.FileField(blank=True, default='', null=True, upload_to='products'),
        ),
        migrations.AlterField(
            model_name='article',
            name='teaser',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
