# Generated by Django 3.1.2 on 2021-01-30 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210129_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='banner',
            field=models.FileField(blank=True, default='', null=True, upload_to='articles/banner'),
        ),
    ]
