# Generated by Django 3.1.2 on 2021-01-23 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20210123_0949'),
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderItem',
            new_name='OrderLineItem',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='lastname',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='name',
        ),
    ]
