# Generated by Django 3.1.2 on 2020-10-25 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Eyes', 'Eyes'), ('Lips', 'Lips'), ('Face', 'Face')], max_length=10)),
                ('brand', models.CharField(default='Brand Name', max_length=120)),
                ('line', models.CharField(default='Line Name', max_length=120)),
                ('lineDescription', models.TextField(blank=True, default='Line Description', null=True)),
                ('product', models.TextField(default='Product Name')),
                ('variant', models.TextField(default='Variant Name')),
                ('productDescription', models.TextField(blank=True, default='Product Description', null=True)),
                ('price', models.DecimalField(decimal_places=2, default='Price', max_digits=1000)),
                ('itemNo', models.IntegerField(default='ItemNo')),
                ('image', models.FileField(upload_to='')),
                ('additionalImages', models.FileField(upload_to='')),
            ],
        ),
    ]
