# Generated by Django 3.1.2 on 2020-12-25 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.CharField(blank=True, choices=[('4', 4), ('1', 1), ('2', 2), ('5', 5), ('3', 3)], max_length=1),
        ),
    ]
