# Generated by Django 3.1.2 on 2021-01-06 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20201226_0047'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.FileField(blank=True, default='', null=True, upload_to='categories'),
        ),
    ]
