# Generated by Django 3.1.2 on 2021-01-07 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_category_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
        migrations.AddField(
            model_name='category',
            name='banner',
            field=models.FileField(blank=True, default='', null=True, upload_to='categories/banner'),
        ),
        migrations.AddField(
            model_name='category',
            name='teaser',
            field=models.FileField(blank=True, default='', null=True, upload_to='categories/teaser'),
        ),
        migrations.AddField(
            model_name='product',
            name='deals',
            field=models.BooleanField(default='False', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='new',
            field=models.BooleanField(default='False', null=True),
        ),
    ]
