# Generated by Django 3.1.2 on 2020-11-14 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20201112_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Lips', 'Lips'), ('Eyes', 'Eyes'), ('Face', 'Face')], max_length=10),
        ),
    ]
