# Generated by Django 3.1.2 on 2021-01-07 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20210106_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='deals',
            field=models.BooleanField(default='False', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='new',
            field=models.BooleanField(default='False', null=True),
        ),
    ]
