# Generated by Django 3.1.2 on 2021-01-07 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20210107_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='favorites',
            field=models.BooleanField(default='No'),
        ),
        migrations.AlterField(
            model_name='product',
            name='deals',
            field=models.BooleanField(default='No', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='new',
            field=models.BooleanField(default='No', null=True),
        ),
    ]
