# Generated by Django 3.1.2 on 2021-01-07 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20210107_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='deals',
            field=models.BooleanField(default='False', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='favorites',
            field=models.BooleanField(default='False'),
        ),
        migrations.AlterField(
            model_name='product',
            name='new',
            field=models.BooleanField(default='False', null=True),
        ),
    ]
