# Generated by Django 3.1.2 on 2020-12-23 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20201223_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='display_name',
            field=models.CharField(default=2, max_length=254),
            preserve_default=False,
        ),
    ]
