# Generated by Django 3.1.2 on 2020-12-23 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_category_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='display_name',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='additionalImages',
            field=models.FileField(blank=True, default='', null=True, upload_to='additional'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.FileField(blank=True, default='', null=True, upload_to='products'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.IntegerField(default='000000'),
        ),
    ]
